/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Collections;
import java.util.List;

import org.bitcorej.chain.*;

public class App {
    public String getGreeting() {
        return "Decker was here! I am not a Java coder =)";
    }

    public static void main(String[] args) {

        try {
            // Attempt to create a ChainStateProxy instance
            ChainStateProxy provider = new ChainStateProxy("zec", "main");

            /*
             *          Network Prefix: 3C
                Compressed Public Key: 02faef4f497fc37fd8e44f7cba0d96b9324c19b20343951c2597923a2d74a8f011
                Uncompressed Public Key: 04faef4f497fc37fd8e44f7cba0d96b9324c19b20343951c2597923a2d74a8f011cc378687f17809a8d4ab807292c055677b95be9e8db7872ad62d018656acc64
                            Private Key: 38cb1b39ad35f3f9402f373ca4dcde2469307fa17d011cf3b21ac3ba74d78967
                        Compressed WIF: UquwdJKHnC8egwm4aQ8WA2sejYAna38iYvxhWgyz97ro4Gvsfahi
                    Uncompressed WIF: 7JsxspRXzN6p4AEcFN6n82nTg6FTBf6NebRrWPCYyfiBtYAmhMJ
                    Compressed Address: RJheMKD57GUTVwySzgdeqXMFuLvAJTtbWb
                Uncompressed Address: RYPuhvA9kacrSxtVgePBqybFUnMQSeZaxC
            */
            
            // KeyPair key = provider.generateKeyPair();
            KeyPair key = provider.generateKeyPair("38cb1b39ad35f3f9402f373ca4dcde2469307fa17d011cf3b21ac3ba74d78967");

            System.out.println("Public key (address): " + key.getPublic());
            System.out.println("Secret key: " + key.getSecret());

            List<String> keys = Collections.singletonList(key.getSecret());
            System.out.println(keys);
            
            String txJSON = """
                    {
                    "inputs": [
                        {
                        "txid": "ddf306c1c7229b3e14767ead6c2c4d2a8f9920eb49d7380fddbaa53b86002fe3",
                        "vout": 1,
                        "output": {
                            "amount": "0.05000000",
                            "script": "76a91467590bd560ce578129e9661c5782ec3fe9e8cc9c88ac"
                        }
                        }
                    ],
                    "outputs": [
                        {
                        "amount": "0.05000000",
                        "script": "76a91467590bd560ce578129e9661c5782ec3fe9e8cc9c88ac"
                        }
                    ]
                    }
                    """;


            System.out.println(txJSON);

            String signedTx = provider.signRawTransaction(txJSON, keys);
            System.out.println(signedTx);

        } catch (Exception e) {
            // Handle the exception appropriately
            System.err.println("An error occurred while initializing ChainStateProxy: " + e.getMessage());
            e.printStackTrace();
        }


        System.out.println(new App().getGreeting());
    }
}
